project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  sidebar:
    style: "docked"
    contents:
          - viz_1_ggplot.qmd
          - viz_2_exploratoryAnalysis.qmd
          - viz_3_exemplarVisualizations.qmd
          - viz_4_building_better.qmd
          - viz_start_to_finish.qmd
    tools: 
      - icon: github
        href: https://github.com/GenomicsAotearoa/visualization_day


format:
  html:
    mainfont: "sarif"
    monofont: "monospace"
    fontsize: 18px
    theme: cosmo
    css: styles.css
    include-after-body: footer.html


